'use client'
import type { Metadata } from "next";
import "./globals.css";
import { Raleway } from "next/font/google";
import ReactQueryProvider from "@/hooks/useProviderQuery";
import { authClient } from "@/lib/auth-client";
import { useRouter } from "next/navigation";


const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-raleway",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const {data: session, isPending } = authClient.useSession()

  if(!session){
    const router = useRouter()
    router.push('/auth/login')
  }

  console.log(session)

  return (
   <html lang="pt-BR" >
    <ReactQueryProvider>
      <body className={`${raleway.className} bg-gray-900 min-h-screen`}>
          {children}
      </body>
    </ReactQueryProvider>
    </html>
  );
}
