import type { Metadata } from "next";
import "./globals.css";
import { Raleway } from "next/font/google";
import ReactQueryProvider from "@/hooks/useProviderQuery";

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-raleway",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  

  return (
   <html lang="pt-BR" >
    <ReactQueryProvider>
      <body className={`${raleway.className} bg-accent-foreground min-h-screen overflow-y-hidden`}>
          {children}
      </body>
    </ReactQueryProvider>
    </html>
  );
}
